version: '2.1'

services:

  file-service:
    container_name: namenode-service
    build: .
    volumes:
      - '.:/usr/src/app'
    ports:
      - 5001:5000 # expose ports - HOST:CONTAINER
    environment:
      - APP_SETTINGS=namenode.config.Config

#  file-service-2:
#    container_name: file-service-2
#    build: .
#    volumes:
#      - '.:/usr/src/app'
#    ports:
#      - 5002:5000 # expose ports - HOST:CONTAINER
#    environment:
#      - APP_SETTINGS=project.config.DevelopmentConfig